### ISSUE TITLE
Wrong indention for newlines after `let` ?

### ISSUE THREAD

**Issue by lesguillemets** [itchyny/vim-haskell-indent#1]
Hi, thanks for your plugins!

I encountered issues regarding indentation for newlines after `let`. Codes like this:

```haskell
-- input 0
f = let
    foo = 3
    in
        print foo
```

or this:

```haskell
-- input 1
f = let foo = bar
        baz = poi
        in putStrLn "mof"
```

are broken after `gg=G`.

```haskell
-- result 0
f = let
foo = 3
       in
       print foo
```

```haskell
-- result 1
f = let foo = bar
baz = poi
        in putStrLn "mof"
```

I have no fixed opinion about the desired result for these examples.

**Comment by itchyny** [comment]
I fixed for the input 1 case at https://github.com/itchyny/vim-haskell-indent/commit/484e7319bb516283096898798f667c4da76f1b0d.

**Comment by lesguillemets** [comment]
Thanks for the very prompt fix. It's working beautifully. 

As for the input 0, I'm still a beginner and had no idea whether it's a common style or not (I only knew that it compiles). So I guess this can be considered to be fixed without support for that style.  Thanks!
