### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Cypher1** [itchyny/vim-haskell-indent#11]
Does vim-haskell-indent require extra installation when using Plug? It doesn't seem to be compatible.
The relevant line of my vrc is

```
Plug 'itchyny/vim-haskell-indent'       " Haskell Indent
```

Thanks

**Comment by itchyny** [comment]
No, this plugin doesn't require extra configuration. Did you try `:PlugInstall` or restarting Vim? I don't use vim-plug but `, { 'for': 'haskell' }` will also help.

**Comment by Cypher1** [comment]
Partially worked it out, I also had haskell-vim installed (forgot that it had an indenter too).

Now I'm having an issue where indentation isn't applied after 'wheres'.
Sorry to bother you further but if you know what the problem is that'd be great.

Thanks

**Comment by Cypher1** [comment]
Thanks, sorted it out haskell-vim had left behind some of its indentation settings.

Awesome plugin @itchyny Thanks :D

**Comment by itchyny** [comment]
OK.
