### ISSUE TITLE
Indentation issue.

### ISSUE THREAD

**Issue by Plevoscoba** [itchyny/vim-haskell-indent#12]
Hi!

I tried your plugin and everything was working pretty fine until I started lurking on the Yesod framework.

There is a problem with the very first example program given [here](http://www.yesodweb.com/book/basics).
The code indentation breaks after the line `instance Yesod HelloWorld`

Is there any chance to fix that?
Thanks in advance!

**Comment by itchyny** [comment]
I tried to fix but I still know that auto indentation does not work well with Quasiquotations. In general auto indentation for Haskell is of much pain, I think this plugin can support while your coding.
