### ISSUE TITLE
associated data family declaration with TypeFamilies

### ISSUE THREAD

**Issue by lesguillemets** [itchyny/vim-haskell-indent#13]
Hi,

I met an issue with the indentation in a code with `TypeFamilies`. This code from the [haskell wiki](https://wiki.haskell.org/GHC/Type_families#The_class_declaration) is de-indented on the `data` line. 

Expected (with 4 spaces):

```haskell
class GMapKey k where
    data Gmap k :: * -> *
    empty :: Gmap k v
```

Currently:

```haskell
class GMapKey k where
data Gmap k :: * -> *
empty :: Gmap k v
```

Edit: similarly in the instance declaration:

```haskell
instance GMapKey Int where
    data GMap Int v = GMapInt (Data.IntMap.IntMap v)
```

**Comment by itchyny** [comment]
I think I have supported these syntaxes.

**Comment by lesguillemets** [comment]
Thank you for the prompt fix. There were no issues as far as I've encountered.
