### ISSUE TITLE
手元のvimでletとwhereの改行後のindentがずれてしまう

### ISSUE THREAD

**Issue by Szkieletor37** [itchyny/vim-haskell-indent#14]
こんにちは。issueを投げることが初めてなので勝手がわからないのですが、どうかご容赦ください。

Haskellで以下のようなlet、whereを使うコードを書いたところ、indentが思った位置に行きませんでした。

```
cylinder :: Double -> Double -> Double
cylinder r h =
	let sideArea = 2 * pi * r * h
     topArea = pi * r ^ 2
     in sideArea + 2 * topArea

```
topAreaがsideAreaと並ぶものだと思っていたのですが、行頭から1タブのところに来ます。

```
describeList' :: [a] -> String
describeList' ls = "The list is " ++ what ls
	where what [] = "empty."
       what [x] = "a singleton list."
       what xs = "a longer list."
```
こちらもwhatが並行になりません。行頭から1タブのところに配置されます。

これは仕様通りでしょうか？

**Comment by itchyny** [comment]
letのあとはletと同じ位置にしたい場合があるので、一つ目は仕様です。
```haskell
f = do
  let x = 0
  y <- return 0
  let z = 0
  w <- return 0
  return (x, y, z, w)
```

二つ目ですが、タブインデントが原因かと思います。vim-haskell-indentはあまりハードタブのケアをしていなくて、スペースインデントしかサポートしていません。すみません。

**Comment by Szkieletor37** [comment]
ありがとうございます。vimでshiftwidthを設定したらふたつ目が上手く行くようになったので、大丈夫です。とても助かっています。
