### ISSUE TITLE
Wrong indentation due to `where` in closed type family

### ISSUE THREAD

**Issue by JakobBruenker** [itchyny/vim-haskell-indent#17]
When writing a closed type family, on pressing enter after writing `where`, the indent is relative to the position of the `where`. However, it should be relative to the beginning of the line.

```haskell
type family Test where
  A                B
```
`A`: Where the cursor should be
`B`: Where the cursor actually ends up

**Comment by itchyny** [comment]
Thanks for your report, this should be fixed.
