### ISSUE TITLE
do-blocks within if then/else produce confusion indentation

### ISSUE THREAD

**Issue by DestyNova** [itchyny/vim-haskell-indent#19]
Hi, I typed the following sample code in, letting the autoindenter decide what to do on each line:

```haskell
main = do
  let n = 1
  if n > 0
     then do
       putStrLn "hello"
       else putStrLn "goodbye"
```
I'm not sure if the way I've ended lines on `do` is good style, but breaking to a new line and writing `do putStrLn "hello"` produces strange results too. The issue here is that the `else` block is aligned too far right. Unfortunately, using `<<` to unindent that line produces this result:

```haskell
  if n > 0
     then do
       putStrLn "hello"
      else putStrLn "goodbye"
```
The `else` was moved just one space left. I think the `else` should be matched to the lexically-enclosing `if` (since you can't have an `if` expression without an `else` in Haskell), and set to the same level as the `then`. Even without that part though, I'm a bit confused by the behaviour of `<<` here.

**Comment by itchyny** [comment]
I fixed this issue.

**Comment by DestyNova** [comment]
Thanks, that works nicely :+1:
