### ISSUE TITLE
Wrong indention for GADT syntax

### ISSUE THREAD

**Issue by foreverbell** [itchyny/vim-haskell-indent#2]
Hello, 

I encountered bugs about indention on GADT syntax when I was writing codes like this,

```
{-# LANGUAGE GADTs #-}

data Expr a where
  I :: Int -> Expr Int
```

The correct indention should indent two spaces just as the above code, but your plugin will give this,

```
{-# LANGUAGE GADTs #-}

data Expr a where
              I :: Int -> Expr Int
```

Since I am not familiar with vimrc's syntax, I don't have any ideas on how to fix this :(

But I think it would be easy to fix, because I have noticed that

```
instance Monad Test where
  return = undefined
```

gives the correct indention :)

**Comment by itchyny** [comment]
Thank you for the issue report.
