### ISSUE TITLE
4 spaces instead of 8 indentation?

### ISSUE THREAD

**Issue by kolayne** [itchyny/vim-haskell-indent#22]
Hello. Thank you for this very useful plugin!

I, however, encountered the problem that it defaults to inserting 8 tabs every time an indentation is expected (even though my `tabstop` is set to 4). Is there a way I can configure this behavior?

**Comment by itchyny** [comment]
Please configure `setlocal shiftwidth=4`.

**Comment by kolayne** [comment]
Perfect, thank you!
