### ISSUE TITLE
multiline function indentation is finicky

### ISSUE THREAD

**Issue by leg7** [itchyny/vim-haskell-indent#23]
if you want to write a function under it's definition the only way to get it indented right is to press enter right after the `=` sign. if there is a space after it like so `= ` and you press enter to go down to the next line then indentation will not be triggered.

This happens quite often when you want to redefine a 1 line function over multiple lines like this:

```myFunction x = undefined```

here I would do `$bC<cr>` and the resulting indentation would be this because the cursor wasn't right after `=` when pressing enter.

```haskell
myFunction x =
someCode
```

**Comment by itchyny** [comment]
Thanks for reporting, I fixed for this case.
