### ISSUE TITLE
Give more trust to the user?

### ISSUE THREAD

**Issue by Futarimiti** [itchyny/vim-haskell-indent#27]
First of all, great thanks for the plugin.

In the following snippet, the `Nothing` case should be aligning against `Just n`. It is wrongfully taken as a further pattern for the inner case expression when indenting:

```haskell
case_ :: Maybe Int -> Int
case_ x = case x of Just n  -> case n of 1 -> 1
                                         _ -> (-1)
                    Nothing -> 0
-- after indent --------------------------------
case3 :: Maybe Int -> Int
case3 x = case x of Just n  -> case n of 1 -> 1
                                         _ -> (-1)
                                         Nothing -> 0
```

Which is not desired. Similarly:

```haskell
class A a where
  aa :: Int
other_function :: () -> ()
other_function = undefined
-- after indent --------------------------------
class A a where
  aa :: Int
  other_function :: () -> ()
  other_function = undefined
```

The list goes on.

**Comment by Futarimiti** [comment]
We are definitely not going to parse or evaluate Haskell code, therefore the best approach I can think of is to just trust the user with their indent as long as it is expected. So going back to the first case:

```haskell
case_ :: Maybe Int -> Int
case_ x = case x of Just n  -> case n of 1 -> 1
                                         _ -> (-1)
```

When writing the next case on a new line, you are expected to continue on either the outer case:

```haskell
case3 :: Maybe Int -> Int
case3 x = case x of Just n  -> case n of 1 -> 1
                                         _ -> (-1)
                    |
```

or the inner case:

```haskell
case3 :: Maybe Int -> Int
case3 x = case x of Just n  -> case n of 1 -> 1
                                         _ -> (-1)
                                         |
```

There are a lot to decide thence. My ideas are:
- if the line has been indented with one of expected number of spaces already, leave it as-is.
- otherwise, indent the line forward with minimal number of spaces. So if the line has no indentation, push it to the outer case; if more indented than inner case, push it back.
- if the line is empty or new, use the farthest indent.
- feel free to share your opinions

At this point I feel like it's already challenging and expect lots of work to be done. It's not like what I could finish in a day, so I'll just leave this issue here for now.

**Comment by itchyny** [comment]
This plugin can be used for support writing code, but not for indenting the entire code. So I don't recommend to apply auto indentation to existing code. But still looks weird, the plugin recognizes `_` case pattern ([where_case.out.hs](https://github.com/itchyny/vim-haskell-indent/blob/master/test/case/where_case.out.hs)). Maybe it fails on some case but patches welcome for this case. Also, for the second case, an empty line would reset the indentation. Anyway, although I'm losing motivation for this plugin but keep merging PRs if resolve some issues.
